services:
    front_synchroniser.path_resolver.symfony:
        class: FrontSynchroniser\PathResolver\SymfonyPathResolver
        arguments: ["@templating.name_parser", "@templating.locator"]

    front_synchroniser.manager:
        class: FrontSynchroniserBundle\Service\FrontSynchroniserManager
        arguments: ["%front_synchroniser%", "@front_synchroniser.path_resolver.symfony"]

    front_synchroniser.finder:
         class: FrontSynchroniserBundle\Service\FrontSynchroniserFinder
         arguments: ["%front_synchroniser%", "@kernel", "@front_synchroniser.manager"]

    front_synchroniser.twig.loader.filesystem:
        class: Symfony\Bundle\TwigBundle\Loader\FilesystemLoader
        arguments: ["@templating.locator", "@templating.name_parser"]
        tags:
            - { name: twig.loader }

    twig.extension.front_synchroniser:
        class: FrontSynchroniserBundle\Twig\Extension\FrontSynchroniserExtension
        arguments: ["@front_synchroniser.manager"]
        tags:
            - { name: twig.extension }
